Repository MPAS-Dev/compass, pull requests merged in 2020-12, with the labels that each got.

#26 Update metapackage to 0.1.12
  recipe/meta.yaml
Labels: metapackage

#33 Add deployment script for compass envs
  deploy/create_compass_env.py
Labels: metapackage

#32 Make sure link/copy sources are absolute paths
  setup_testcase.py
Labels: enhancement

#35 Update LANL hpc links after they changed
  docs/machine_specific_instructions/lanl.rst
Labels: documentation
