Repository MPAS-Dev/compass, pull requests merged in 2021-06, with the labels that each got.

#117 Significantly change how to create development conda environments
  .gitignore
  azure-pipelines.yml
  compass/default.cfg
  compass/setup.py
  compass/suite.py
  conda/.gitignore
  conda/compass_env/build.template
  conda/compass_env/config_compilers.xml
  conda/compass_env/config_machines.xml
  conda/compass_env/load_compass.template
  conda/compass_env/spec-file-mpich.txt
  conda/compass_env/spec-file-nompi.txt
  conda/compass_env/spec-file-openmpi.txt
  conda/configure_compass_env.py
  conda/recipe/conda_build_config.yaml
  conda/recipe/meta.yaml
  conda/unsupported.txt
  deploy/create_compass_env.py
  deploy/load_compass.template
  docs/developers_guide/building_docs.rst
  docs/developers_guide/command_line.rst
  docs/developers_guide/machines/anvil.rst
  docs/developers_guide/machines/badger.rst
  docs/developers_guide/machines/chrysalis.rst
  docs/developers_guide/machines/compy.rst
  docs/developers_guide/machines/cori.rst
  docs/developers_guide/machines/grizzly.rst
  docs/developers_guide/machines/index.rst
  docs/developers_guide/quick_start.rst
  docs/users_guide/landice/suites.rst
  docs/users_guide/ocean/suites.rst
  docs/users_guide/test_suites.rst
  load/get_activation_script.py
  load/load_compass_env.sh
  recipe/LICENSE
  recipe/build_and_upload.bash
  recipe/create_new_compass_env.bash
Labels: enhancement, python package

#126 Modify `srun` calls so compass works on Compy
  compass/machines/compy.cfg
  compass/model.py
  conda/compass_env/spec-file-mpich.txt
  conda/compass_env/spec-file-nompi.txt
  conda/compass_env/spec-file-openmpi.txt
  conda/recipe/meta.yaml
  docs/developers_guide/machines/compy.rst
  docs/developers_guide/machines/index.rst
  docs/index.rst
  docs/users_guide/machines/compy.rst
Labels: enhancement, python package

#104 Alter `steps_to_run` in config file or command line
  compass/default.cfg
  compass/run.py
  compass/setup.py
  docs/developers_guide/command_line.rst
Labels: enhancement, python package

#131 Simplify and generalize the `download()` function
  compass/io.py
  compass/step.py
Labels: clean-up, python package

#130 Rename dev. conda env. from `test_compass*` to `dev_compass*`
  conda/configure_compass_env.py
  docs/developers_guide/machines/anvil.rst
  docs/developers_guide/machines/badger.rst
  docs/developers_guide/machines/chrysalis.rst
  docs/developers_guide/machines/compy.rst
  docs/developers_guide/machines/cori.rst
  docs/developers_guide/machines/grizzly.rst
  docs/developers_guide/machines/index.rst
  docs/developers_guide/quick_start.rst
Labels: clean-up, python package

#127 Fix pattern for xml search
  list_testcases.py
Labels: bug, legacy

#134 Add flake8 to development environments
  conda/compass_env/spec-file-mpich.txt
  conda/compass_env/spec-file-nompi.txt
  conda/compass_env/spec-file-openmpi.txt
Labels: python package

#137 Add make to dev environments
  conda/compass_env/spec-file-mpich.txt
  conda/compass_env/spec-file-openmpi.txt
Labels: bug, python package

#139 Fix rounding of test and suite runtimes
  compass/run.py
Labels: bug, python package

#136 Provide flake8 info in Developer's Guide
  docs/developers_guide/overview.rst
Labels: documentation, python package

#138 Add a copy option for input files
  compass/step.py
  docs/developers_guide/framework.rst
  docs/developers_guide/organization.rst
Labels: enhancement, python package

#141 Allow `compass run suitename` to include or not the .pickle suffix
  compass/run.py
  docs/developers_guide/command_line.rst
  docs/users_guide/quick_start.rst
Labels: enhancement, python package

#132 Make 'compass list --suites -v' print the contents of a suite
  compass/list.py
  compass/suite.py
  docs/developers_guide/organization.rst
  docs/users_guide/test_suites.rst
Labels: documentation, enhancement, python package

#142 Move `namelist.update` and `model.update_namelist_pio` into `Step`
  compass/model.py
  compass/namelist.py
  compass/ocean/iceshelf.py
  compass/ocean/tests/global_convergence/cosine_bell/forward.py
  compass/step.py
  docs/developers_guide/api.rst
  docs/developers_guide/docs.rst
  docs/developers_guide/framework.rst
  docs/developers_guide/organization.rst
Labels: clean-up, python package

#143 Update mpas_tools to 0.7.0
  conda/compass_env/spec-file-mpich.txt
  conda/compass_env/spec-file-nompi.txt
  conda/compass_env/spec-file-openmpi.txt
  conda/recipe/meta.yaml
  setup.py
Labels: python package

#144 Fix updating namelist in gotm/default test case
  compass/ocean/tests/gotm/default/init.py
Labels: bug, ocean, python package

#118 Reorganize ocean vertical module
  compass/ocean/iceshelf.py
  compass/ocean/tests/baroclinic_channel/baroclinic_channel.cfg
  compass/ocean/tests/baroclinic_channel/initial_state.py
  compass/ocean/tests/global_ocean/init/initial_state.py
  compass/ocean/tests/ice_shelf_2d/ice_shelf_2d.cfg
  compass/ocean/tests/ice_shelf_2d/initial_state.py
  compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py
  compass/ocean/tests/ziso/default/__init__.py
  compass/ocean/tests/ziso/initial_state.py
  compass/ocean/tests/ziso/ziso.cfg
  compass/ocean/vertical/__init__.py
  compass/ocean/vertical/grid_1d.py
  compass/ocean/vertical/partial_cells.py
  compass/ocean/vertical/zlevel.py
  compass/ocean/vertical/zstar.py
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/framework.rst
  docs/users_guide/ocean/framework/vertical.rst
  docs/users_guide/ocean/test_groups/baroclinic_channel.rst
  docs/users_guide/ocean/test_groups/ice_shelf_2d.rst
  docs/users_guide/ocean/test_groups/ziso.rst
Labels: enhancement, ocean, python package

#147 Update example config files
  example_configs/landice.cfg
  example_configs/ocean.cfg
Labels: clean-up, python package

#146 Add FO versions of Greenland test cases
  compass/landice/suites/fo_integration.txt
  compass/landice/suites/full_integration.txt
  compass/landice/suites/sia_integration.txt
  compass/landice/tests/dome/decomposition_test/__init__.py
  compass/landice/tests/greenland/__init__.py
  compass/landice/tests/greenland/decomposition_test/__init__.py
  compass/landice/tests/greenland/restart_test/__init__.py
  compass/landice/tests/greenland/run_model.py
  compass/landice/tests/greenland/smoke_test/__init__.py
  docs/users_guide/landice/test_groups/greenland.rst
  docs/users_guide/landice/test_groups/images/gis_speed.png
Labels: land ice, python package

#148 Add Albany yaml files specific to Greenland configuration
  compass/landice/tests/greenland/albany_input.yaml
  compass/landice/tests/greenland/albany_schoof_input.yaml
  compass/landice/tests/greenland/run_model.py
Labels: clean-up, land ice, python package

#150 Some fixes to docstrings and documentation
  compass/ocean/vertical/__init__.py
  compass/ocean/vertical/zlevel.py
  compass/ocean/vertical/zstar.py
  docs/developers_guide/organization.rst
Labels: clean-up, documentation, python package

#152 Fix appending of global ocean metadata
  compass/ocean/tests/global_ocean/metadata.py
Labels: bug, ocean, python package

#153 Add missing output files to 3 ocean test groups
  compass/ocean/tests/global_ocean/analysis_test/__init__.py
  compass/ocean/tests/ice_shelf_2d/__init__.py
  compass/ocean/tests/ice_shelf_2d/forward.py
  compass/ocean/tests/ziso/forward.py
Labels: bug, ocean, python package

#151 Check that files to validate are step output
  compass/setup.py
  compass/validate.py
  docs/developers_guide/framework.rst
Labels: enhancement, python package

#128 Add a tutorial on porting test groups from legacy
  docs/developers_guide/quick_start.rst
  docs/glossary.rst
  docs/index.rst
  docs/tutorials/dev_porting_legacy.rst
Labels: documentation, python package

#156 Switch dev environment creation to use mamba
  .gitignore
  conda/configure_compass_env.py
Labels: clean-up, python package

#149 Add Thwaites 4km test group to landice core
  compass/landice/__init__.py
  compass/landice/suites/fo_integration.txt
  compass/landice/suites/full_integration.txt
  compass/landice/tests/thwaites/__init__.py
  compass/landice/tests/thwaites/albany_input.yaml
  compass/landice/tests/thwaites/decomposition_test/__init__.py
  compass/landice/tests/thwaites/namelist.landice
  compass/landice/tests/thwaites/restart_test/__init__.py
  compass/landice/tests/thwaites/restart_test/namelist.full
  compass/landice/tests/thwaites/restart_test/namelist.restart
  compass/landice/tests/thwaites/restart_test/namelist.restart.rst
  compass/landice/tests/thwaites/restart_test/streams.full
  compass/landice/tests/thwaites/restart_test/streams.restart
  compass/landice/tests/thwaites/run_model.py
  compass/landice/tests/thwaites/streams.landice
  docs/developers_guide/landice/api.rst
  docs/developers_guide/landice/test_groups/greenland.rst
  docs/developers_guide/landice/test_groups/index.rst
  docs/developers_guide/landice/test_groups/thwaites.rst
  docs/users_guide/landice/suites.rst
  docs/users_guide/landice/test_groups/greenland.rst
  docs/users_guide/landice/test_groups/images/thwaites_speed.png
  docs/users_guide/landice/test_groups/index.rst
  docs/users_guide/landice/test_groups/thwaites.rst
Labels: land ice, python package

#155 Skip steps not run by default in validation
  compass/landice/tests/dome/decomposition_test/__init__.py
  compass/landice/tests/dome/restart_test/__init__.py
  compass/landice/tests/eismint2/decomposition_test/__init__.py
  compass/landice/tests/eismint2/restart_test/__init__.py
  compass/landice/tests/greenland/decomposition_test/__init__.py
  compass/landice/tests/greenland/restart_test/__init__.py
  compass/landice/tests/hydro_radial/decomposition_test/__init__.py
  compass/landice/tests/hydro_radial/restart_test/__init__.py
  compass/landice/tests/thwaites/decomposition_test/__init__.py
  compass/landice/tests/thwaites/restart_test/__init__.py
  compass/ocean/tests/baroclinic_channel/decomp_test/__init__.py
  compass/ocean/tests/baroclinic_channel/restart_test/__init__.py
  compass/ocean/tests/baroclinic_channel/threads_test/__init__.py
  compass/ocean/tests/global_ocean/decomp_test/__init__.py
  compass/ocean/tests/global_ocean/init/__init__.py
  compass/ocean/tests/global_ocean/restart_test/__init__.py
  compass/ocean/tests/global_ocean/threads_test/__init__.py
  compass/ocean/tests/gotm/default/__init__.py
  compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py
  compass/ocean/tests/ziso/default/__init__.py
  compass/ocean/tests/ziso/with_frazil/__init__.py
  compass/validate.py
  docs/developers_guide/framework.rst
  docs/developers_guide/organization.rst
  docs/tutorials/dev_porting_legacy.rst
Labels: clean-up, land ice, ocean, python package

#159 Add Haney number module to ocean framework
  compass/ocean/haney.py
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/framework.rst
  docs/developers_guide/ocean/images/haney.png
Labels: enhancement, ocean, python package

#120 Add z-level ice-shelf 2d test cases
  compass/ocean/suites/nightly.txt
  compass/ocean/tests/ice_shelf_2d/__init__.py
  compass/ocean/tests/ice_shelf_2d/default/__init__.py
  compass/ocean/tests/ice_shelf_2d/ice_shelf_2d.cfg
  compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py
  compass/ocean/tests/ice_shelf_2d/viz.py
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/test_groups/ice_shelf_2d.rst
  docs/users_guide/ocean/test_groups/ice_shelf_2d.rst
Labels: enhancement, ocean, python package

#161 Fix typos in `files_for_e3ms` docstring
  compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
Labels: documentation, ocean, python package

#162 Fix activation script name when `--env_name` flag is used
  conda/configure_compass_env.py
Labels: python package

#163 Fix None check of norms in validate package
  compass/validate.py
Labels: bug, python package

#160 Update Atlantic MOC basins to exclude Mediterranean
  conda/compass_env/spec-file-mpich.txt
  conda/compass_env/spec-file-nompi.txt
  conda/compass_env/spec-file-openmpi.txt
  conda/recipe/meta.yaml
Labels: enhancement, in progress, python package

#158 Add z-star ISOMIP+ Ocean0 test case
  compass/ocean/__init__.py
  compass/ocean/tests/isomip_plus/__init__.py
  compass/ocean/tests/isomip_plus/evap.py
  compass/ocean/tests/isomip_plus/forward.py
  compass/ocean/tests/isomip_plus/geom.py
  compass/ocean/tests/isomip_plus/initial_state.py
  compass/ocean/tests/isomip_plus/isomip_plus.cfg
  compass/ocean/tests/isomip_plus/misomip.py
  compass/ocean/tests/isomip_plus/namelist.forward
  compass/ocean/tests/isomip_plus/namelist.forward_and_ssh_adjust
  compass/ocean/tests/isomip_plus/ocean_test/__init__.py
  compass/ocean/tests/isomip_plus/ssh_adjustment.py
  compass/ocean/tests/isomip_plus/streamfunction.py
  compass/ocean/tests/isomip_plus/streams.forward.template
  compass/ocean/tests/isomip_plus/viz/__init__.py
  compass/ocean/tests/isomip_plus/viz/plot.py
  conda/compass_env/spec-file-mpich.txt
  conda/compass_env/spec-file-nompi.txt
  conda/compass_env/spec-file-openmpi.txt
  conda/recipe/meta.yaml
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/test_groups/index.rst
  docs/developers_guide/ocean/test_groups/isomip_plus.rst
  docs/users_guide/ocean/test_groups/images/isomip_plus.png
  docs/users_guide/ocean/test_groups/index.rst
  docs/users_guide/ocean/test_groups/isomip_plus.rst
  setup.py
Labels: enhancement, ocean, python package

#167 Add landice circular shelf test group
  compass/landice/__init__.py
  compass/landice/suites/fo_integration.txt
  compass/landice/suites/full_integration.txt
  compass/landice/tests/circular_shelf/__init__.py
  compass/landice/tests/circular_shelf/albany_input.yaml
  compass/landice/tests/circular_shelf/circular_shelf.cfg
  compass/landice/tests/circular_shelf/decomposition_test/__init__.py
  compass/landice/tests/circular_shelf/namelist.landice
  compass/landice/tests/circular_shelf/run_model.py
  compass/landice/tests/circular_shelf/setup_mesh.py
  compass/landice/tests/circular_shelf/streams.landice
  compass/landice/tests/circular_shelf/visualize.py
  docs/developers_guide/landice/api.rst
  docs/developers_guide/landice/test_groups/circular_shelf.rst
  docs/developers_guide/landice/test_groups/index.rst
  docs/users_guide/landice/index.rst
  docs/users_guide/landice/suites.rst
  docs/users_guide/landice/test_groups/circular_shelf.rst
  docs/users_guide/landice/test_groups/images/circ_shelf_velos.png
  docs/users_guide/landice/test_groups/images/circ_shelf_xsect.png
  docs/users_guide/landice/test_groups/index.rst
Labels: documentation, land ice, python package

#168 Add ISOMIP+ Ocean1 and Ocean2 test cases
  compass/ocean/tests/isomip_plus/__init__.py
  compass/ocean/tests/isomip_plus/ocean_test/__init__.py
  docs/developers_guide/ocean/test_groups/isomip_plus.rst
  docs/users_guide/ocean/test_groups/isomip_plus.rst
Labels: enhancement, ocean, python package

#77 Mixed layer eddy test cases
  ocean/mixed_layer_eddy/0.6km/double_front/config_driver.xml
  ocean/mixed_layer_eddy/0.6km/double_front/config_forward.xml
  ocean/mixed_layer_eddy/0.6km/double_front/config_init.xml
  ocean/mixed_layer_eddy/0.6km/single_front/config_driver.xml
  ocean/mixed_layer_eddy/0.6km/single_front/config_forward.xml
  ocean/mixed_layer_eddy/0.6km/single_front/config_init.xml
Labels: MPAS-Model PR required, legacy, ocean

#169 Fix Dev Guide typos
  docs/developers_guide/framework.rst
Labels: documentation, python package

#157 Switch Linux and OSX environments to use SCORPIO conda package
  conda/compass_env/spec-file-mpich.txt
  conda/compass_env/spec-file-openmpi.txt
  conda/configure_compass_env.py
  conda/pnetcdf/ci/linux_mpi_mpich.yaml
  conda/pnetcdf/ci/linux_mpi_openmpi.yaml
  conda/pnetcdf/ci/osx_mpi_mpich.yaml
  conda/pnetcdf/ci/osx_mpi_openmpi.yaml
  conda/pnetcdf/recipe/build.sh
  conda/pnetcdf/recipe/conda_build_config.yaml
  conda/pnetcdf/recipe/meta.yaml
  conda/pnetcdf/recipe/run_test.sh
  conda/scorpio/ci/linux_mpi_mpich.yaml
  conda/scorpio/ci/linux_mpi_openmpi.yaml
  conda/scorpio/ci/osx_mpi_mpich.yaml
  conda/scorpio/ci/osx_mpi_openmpi.yaml
  conda/scorpio/recipe/COPYRIGHT
  conda/scorpio/recipe/build.sh
  conda/scorpio/recipe/conda_build_config.yaml
  conda/scorpio/recipe/meta.yaml
Labels: enhancement, python package

#170 Fix use of "~" in conda base location
  conda/configure_compass_env.py
Labels: bug, python package
