Repository MPAS-Dev/compass, pull requests merged in 2021-07, with the labels that each got.

#173 Add Cori-KNL gnu to unsupported compilers
  conda/configure_compass_env.py
  conda/unsupported.txt
  docs/developers_guide/machines/cori.rst
  docs/developers_guide/machines/index.rst
Labels: python package

#174 Add a troubleshooting section to the developer's guide
  docs/developers_guide/framework.rst
  docs/developers_guide/troubleshooting.rst
  docs/index.rst
Labels: documentation, python package

#176 Fix typos in the README
  README.md
Labels: documentation, python package

#178 Better document and configure conda envs. on Linux and Mac OS
  conda/configure_compass_env.py
  docs/developers_guide/machines/index.rst
  docs/developers_guide/quick_start.rst
Labels: documentation, python package

#179 Switch to using a template for dev-spec files
  conda/compass_env/spec-file-nompi.txt
  conda/compass_env/spec-file-openmpi.txt
  conda/compass_env/spec-file.template
  conda/configure_compass_env.py
  docs/developers_guide/troubleshooting.rst
Labels: python package

#180 Update `mpas_tools` to 0.8.0
  conda/compass_env/spec-file.template
  conda/recipe/meta.yaml
Labels: python package

#182 Add troubleshooting proxy issues on LANL Macs
  docs/developers_guide/troubleshooting.rst
Labels: documentation, python package

#181 Move "Building MPAS components" earlier in the developer's quick start
  docs/developers_guide/quick_start.rst
Labels: documentation, python package

#183 Update Quick Start for Developers
  docs/developers_guide/quick_start.rst
Labels: documentation, python package

#190 Set ISOMIP+ cores and min_cores during setup
  compass/ocean/tests/isomip_plus/ocean_test/__init__.py
Labels: bug, ocean, python package

#171 Update scorpio to 1.2.1
  compass/default.cfg
  compass/machines/anvil.cfg
  conda/compass_env/build.template
  conda/compass_env/config_compilers.xml
  conda/compass_env/config_machines.xml
  conda/compass_env/spec-file.template
  conda/configure_compass_env.py
  conda/scorpio/recipe/build.sh
  conda/scorpio/recipe/meta.yaml
  conda/unsupported.txt
  docs/developers_guide/machines/anvil.rst
  docs/developers_guide/machines/index.rst
  docs/users_guide/machines/anvil.rst
Labels: enhancement, python package

#187 Add support for specifying the NetCDF output engine
  compass/default.cfg
  compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
  compass/ocean/tests/global_ocean/mesh/cull.py
  compass/run.py
  conda/compass_env/spec-file.template
  conda/recipe/meta.yaml
Labels: enhancement, python package
