Repository MPAS-Dev/compass, pull requests merged in 2022-07, with the labels that each got.

#370 Add single layer drying slope case
  compass/ocean/tests/drying_slope/__init__.py
  compass/ocean/tests/drying_slope/default/__init__.py
  compass/ocean/tests/drying_slope/drying_slope.cfg
  compass/ocean/tests/drying_slope/forward.py
  compass/ocean/tests/drying_slope/initial_state.py
  compass/ocean/tests/drying_slope/namelist.forward
  compass/ocean/tests/drying_slope/namelist.init
  compass/ocean/tests/drying_slope/namelist.sigma.forward
  compass/ocean/tests/drying_slope/namelist.single_layer.forward
  compass/ocean/tests/drying_slope/viz/__init__.py
  docs/developers_guide/ocean/test_groups/drying_slope.rst
  docs/users_guide/ocean/test_groups/drying_slope.rst
Labels: enhancement, ocean

#390 Add hurricane cases from legacy compass
  compass/ocean/__init__.py
  compass/ocean/tests/global_ocean/global_ocean.cfg
  compass/ocean/tests/global_ocean/mesh/mesh.py
  compass/ocean/tests/hurricane/__init__.py
  compass/ocean/tests/hurricane/analysis/__init__.py
  compass/ocean/tests/hurricane/analysis/sandy_stations.json
  compass/ocean/tests/hurricane/configure.py
  compass/ocean/tests/hurricane/forward/__init__.py
  compass/ocean/tests/hurricane/forward/forward.py
  compass/ocean/tests/hurricane/forward/namelist.ocean
  compass/ocean/tests/hurricane/forward/streams.ocean
  compass/ocean/tests/hurricane/init/__init__.py
  compass/ocean/tests/hurricane/init/create_pointstats_file.py
  compass/ocean/tests/hurricane/init/initial_state.py
  compass/ocean/tests/hurricane/init/interpolate_atm_forcing.py
  compass/ocean/tests/hurricane/init/namelist.init
  compass/ocean/tests/hurricane/init/streams.init
  compass/ocean/tests/hurricane/mesh/__init__.py
  compass/ocean/tests/hurricane/mesh/dequ120at30cr10rr2/__init__.py
  compass/ocean/tests/hurricane/mesh/dequ120at30cr10rr2/dequ120at30cr10rr2.cfg
  compass/ocean/tests/hurricane/mesh/dequ120at30cr10rr2/namelist.ocean
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/test_groups/hurricane.rst
  docs/developers_guide/ocean/test_groups/index.rst
  docs/users_guide/ocean/test_groups/hurricane.rst
  docs/users_guide/ocean/test_groups/index.rst
Labels: enhancement, ocean

#418 Fix calls to `logger.exception()` not in `except` block
  compass/run/serial.py
Labels: bug, framework

#419 Add `.nml` files to python package
  setup.py
Labels: bug

#415 Update to v1.1.0
  compass/version.py
  conda/recipe/meta.yaml
  docs/versions.rst
Labels: deployment

#420 Update to v1.2.0-alpha.1
  compass/machines/cori-haswell.cfg
  compass/version.py
  conda/albany_supported.txt
  conda/compass_env/spec-file.template
  conda/configure_compass_env.py
  conda/recipe/meta.yaml
  conda/unsupported.txt
  docs/developers_guide/machines/index.rst
  utils/matrix/setup_matrix.py
Labels: deployment

#421 Fix symlinks to latest compass load scripts
  conda/bootstrap.py
Labels: bug, deployment

#423 Give log path for failed tests only in suite
  compass/run/serial.py
Labels: bug, clean-up, framework

#424 Fix namelist errors in internal_wave
  compass/ocean/tests/internal_wave/initial_state.py
Labels: bug, ocean

#411 Add monthly output test and update daily output test to match
  compass/ocean/tests/global_ocean/__init__.py
  compass/ocean/tests/global_ocean/daily_output_test/streams.forward
  compass/ocean/tests/global_ocean/monthly_output_test/__init__.py
  compass/ocean/tests/global_ocean/monthly_output_test/namelist.forward
  compass/ocean/tests/global_ocean/monthly_output_test/streams.forward
Labels: enhancement, ocean, E3SM PR finished

#427 Fix prefix for compass env script in tutorials
  docs/tutorials/dev_add_test_group.rst
  docs/tutorials/dev_porting_legacy.rst
Labels: bug, documentation

#425 Add function for logging function calls
  compass/logging.py
Labels: enhancement, framework

#422 Add jigsaw spherical mesh steps
  compass/mesh/__init__.py
  compass/mesh/mesh.cfg
  compass/mesh/spherical.py
  compass/ocean/cached_files.json
  compass/ocean/suites/cosine_bell_cached_init.txt
  compass/ocean/suites/pr.txt
  compass/ocean/tests/global_convergence/__init__.py
  compass/ocean/tests/global_convergence/cosine_bell/__init__.py
  compass/ocean/tests/global_convergence/cosine_bell/analysis.py
  compass/ocean/tests/global_convergence/cosine_bell/cosine_bell.cfg
  compass/ocean/tests/global_convergence/cosine_bell/forward.py
  compass/ocean/tests/global_convergence/cosine_bell/init.py
  docs/developers_guide/api.rst
  docs/developers_guide/framework.rst
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/test_groups/global_convergence.rst
  docs/users_guide/ocean/test_groups/global_convergence.rst
Labels: enhancement, ocean, framework
