Repository MPAS-Dev/compass, pull requests merged in 2022-06, with the labels that each got.

#403 Remove redundant default argument values
  compass/run/serial.py
Labels: clean-up, framework

#405 Remove all occurrences of "max_disk"
  compass/ocean/tests/global_ocean/global_ocean.cfg
  compass/ocean/tests/global_ocean/mesh/ec30to60/ec30to60.cfg
  compass/ocean/tests/global_ocean/mesh/qu240/qu240.cfg
  compass/ocean/tests/global_ocean/mesh/so12to60/so12to60.cfg
  compass/ocean/tests/global_ocean/mesh/wc14/wc14.cfg
  compass/step.py
Labels: ocean, clean-up, framework

#404 Constrain mamba to avoid recent issue
  conda/shared.py
Labels: bug, deployment

#409 Fix automatic choice of compiler and MPI for OSX
  compass/machines/conda-osx.cfg
  conda/bootstrap.py
Labels: bug, deployment

#412 Rename job script template
  compass/job/__init__.py
  compass/job/job_script.template
Labels: bug, framework
