Repository MPAS-Dev/compass, pull requests merged in 2022-11, with the labels that each got.

#453 Switch to mambaforge and add mamba init
  conda/bootstrap.py
  conda/configure_compass_env.py
  conda/shared.py
Labels: deployment

#455 Remove all references to badger
  compass/machines/badger.cfg
  conda/albany_supported.txt
  conda/spack/badger_gnu_mvapich.yaml
  conda/spack/badger_gnu_openmpi.yaml
  conda/unsupported.txt
  docs/design_docs/compass_package.rst
  docs/developers_guide/machines/badger.rst
  docs/developers_guide/machines/index.rst
  docs/developers_guide/quick_start.rst
  docs/users_guide/machines/badger.rst
  docs/users_guide/machines/index.rst
  docs/users_guide/quick_start.rst
  utils/matrix/setup_matrix.py
Labels: documentation, clean-up

#446 Add support for perlmutter CPU nodes
  compass/machines/pm-cpu.cfg
  compass/parallel.py
  compass/run/serial.py
  compass/version.py
  conda/albany_supported.txt
  conda/compass_env/spec-file.template
  conda/configure_compass_env.py
  conda/recipe/meta.yaml
  docs/developers_guide/machines/index.rst
  docs/developers_guide/machines/perlmutter.rst
  docs/users_guide/machines/index.rst
  docs/users_guide/machines/perlmutter.rst
  docs/users_guide/quick_start.rst
  utils/matrix/setup_matrix.py
Labels: enhancement, deployment

#457 Add error message for namelist replacements
  compass/namelist.py
Labels: enhancement, framework

#459 Update ocean test case namelists
  compass/ocean/tests/baroclinic_channel/namelist.forward
  compass/ocean/tests/global_ocean/init/namelist.init
  compass/ocean/tests/global_ocean/namelist.forward
  compass/ocean/tests/internal_wave/namelist.forward
  compass/ocean/tests/internal_wave/ten_day_test/namelist.forward
  compass/ocean/tests/isomip_plus/namelist.forward_and_ssh_adjust
  compass/ocean/tests/soma/namelist.forward
  compass/ocean/tests/ziso/namelist.forward
Labels: bug, ocean

#452 Port merry-go-round test group from legacy
  compass/ocean/__init__.py
  compass/ocean/tests/merry_go_round/__init__.py
  compass/ocean/tests/merry_go_round/convergence_test/__init__.py
  compass/ocean/tests/merry_go_round/convergence_test/analysis.py
  compass/ocean/tests/merry_go_round/default/__init__.py
  compass/ocean/tests/merry_go_round/forward.py
  compass/ocean/tests/merry_go_round/initial_state.py
  compass/ocean/tests/merry_go_round/merry_go_round.cfg
  compass/ocean/tests/merry_go_round/namelist.forward
  compass/ocean/tests/merry_go_round/streams.forward
  compass/ocean/tests/merry_go_round/viz.py
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/test_groups/index.rst
  docs/developers_guide/ocean/test_groups/merry_go_round.rst
  docs/users_guide/ocean/test_groups/images/merry-go-round_convergence.png
  docs/users_guide/ocean/test_groups/images/merry-go-round_section.png
  docs/users_guide/ocean/test_groups/index.rst
  docs/users_guide/ocean/test_groups/merry_go_round.rst
Labels: enhancement, ocean

#410 Add ismip6 forcing testgroup
  compass/landice/__init__.py
  compass/landice/tests/ismip6_forcing/__init__.py
  compass/landice/tests/ismip6_forcing/atmosphere/__init__.py
  compass/landice/tests/ismip6_forcing/atmosphere/create_mapfile_smb.py
  compass/landice/tests/ismip6_forcing/atmosphere/process_smb.py
  compass/landice/tests/ismip6_forcing/atmosphere/process_smb_racmo.py
  compass/landice/tests/ismip6_forcing/configure.py
  compass/landice/tests/ismip6_forcing/create_mapfile.py
  compass/landice/tests/ismip6_forcing/ismip6_forcing.cfg
  compass/landice/tests/ismip6_forcing/ocean_basal/__init__.py
  compass/landice/tests/ismip6_forcing/ocean_basal/process_basal_melt.py
  compass/landice/tests/ismip6_forcing/ocean_thermal/__init__.py
  compass/landice/tests/ismip6_forcing/ocean_thermal/process_thermal_forcing.py
  docs/developers_guide/landice/api.rst
  docs/developers_guide/landice/test_groups/index.rst
  docs/developers_guide/landice/test_groups/ismip6_forcing.rst
  docs/users_guide/landice/test_groups/index.rst
  docs/users_guide/landice/test_groups/ismip6_forcing.rst
Labels: enhancement, land ice

#466 Add a utility for testing updates to E3SM submodule
  utils/e3sm_update/README.md
  utils/e3sm_update/example.cfg
  utils/e3sm_update/test_e3sm_changes.py
Labels: utility
