Repository MPAS-Dev/compass, pull requests merged in 2022-10, with the labels that each got.

#436 Remove `--exclusive` flag from slurm steps
  compass/parallel.py
Labels: bug, framework

#360 Copy MPAS model executable to work directory
  compass/default.cfg
  compass/setup.py
  compass/step.py
  compass/suite.py
  docs/users_guide/quick_start.rst
Labels: enhancement, framework

#354 Add scripts for using `git bisect`
  utils/bisect/README.md
  utils/bisect/bisect.py
  utils/bisect/bisect_step.py
  utils/bisect/example.cfg
Labels: enhancement, utility

#438 Drop compass_ prefix from job script names
  compass/job/__init__.py
Labels: clean-up, framework

#439 Fix job script name in matrix utility
  utils/matrix/setup_matrix.py
Labels: bug, utility

#443 Switch from 2- to 4-digit year in global ocean
  compass/ocean/tests/global_ocean/make_diagnostics_files/__init__.py
  compass/ocean/tests/global_ocean/metadata.py
Labels: ocean, clean-up

#445 spelling typo
  compass/landice/tests/koge_bugt_s/mesh.py
Labels: clean-up

#441 Add wetdry suite
  compass/ocean/suites/wetdry.txt
Labels: enhancement, ocean

#447 Add more projection grids to diagnostics_files
  compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
  compass/ocean/tests/global_ocean/global_ocean.cfg
  compass/ocean/tests/global_ocean/make_diagnostics_files/__init__.py
  conda/compass_env/spec-file.template
  conda/recipe/meta.yaml
  setup.py
Labels: enhancement, ocean, clean-up

#442 Add a sigma vertical coordinate to ocean framework
  compass/ocean/tests/isomip_plus/__init__.py
  compass/ocean/tests/isomip_plus/initial_state.py
  compass/ocean/tests/isomip_plus/ocean_test/__init__.py
  compass/ocean/tests/isomip_plus/viz/plot.py
  compass/ocean/vertical/__init__.py
  compass/ocean/vertical/sigma.py
Labels: bug, enhancement, ocean
