Repository MPAS-Dev/compass, pull requests merged in 2022-04, with the labels that each got.

#349 Fix how docs detects compass version
  docs/conf.py
Labels: bug, documentation

#355 Add error check for cores not set
  compass/setup.py
Labels: clean-up, framework

#356 Fix docs deployment on tag
  azure-pipelines.yml
Labels: bug, ci

#344 Add a customized config parser
  compass/cache.py
  compass/config.py
  compass/io.py
  compass/landice/tests/circular_shelf/setup_mesh.py
  compass/landice/tests/circular_shelf/visualize.py
  compass/landice/tests/dome/setup_mesh.py
  compass/landice/tests/dome/visualize.py
  compass/landice/tests/eismint2/standard_experiments/visualize.py
  compass/landice/tests/hydro_radial/visualize.py
  compass/model.py
  compass/ocean/plot.py
  compass/ocean/tests/baroclinic_channel/__init__.py
  compass/ocean/tests/global_convergence/cosine_bell/__init__.py
  compass/ocean/tests/global_ocean/configure.py
  compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
  compass/ocean/tests/global_ocean/make_diagnostics_files/__init__.py
  compass/ocean/tests/global_ocean/metadata.py
  compass/ocean/tests/ice_shelf_2d/__init__.py
  compass/ocean/tests/planar_convergence/conv_test_case.py
  compass/ocean/tests/sphere_transport/correlated_tracers_2d/__init__.py
  compass/ocean/tests/sphere_transport/divergent_2d/__init__.py
  compass/ocean/tests/sphere_transport/nondivergent_2d/__init__.py
  compass/ocean/tests/sphere_transport/rotation_2d/__init__.py
  compass/ocean/tests/ziso/__init__.py
  compass/ocean/vertical/__init__.py
  compass/ocean/vertical/grid_1d.py
  compass/ocean/vertical/partial_cells.py
  compass/ocean/vertical/zlevel.py
  compass/ocean/vertical/zstar.py
  compass/parallel.py
  compass/provenance.py
  compass/run.py
  compass/setup.py
  compass/step.py
  compass/testcase.py
  docs/developers_guide/api.rst
  docs/developers_guide/framework.rst
  docs/users_guide/config_files.rst
Labels: framework

#353 Switch to building system libraries with Spack
  compass/machines/anvil.cfg
  compass/machines/badger.cfg
  compass/machines/chrysalis.cfg
  compass/machines/compy.cfg
  compass/machines/conda-linux.cfg
  compass/machines/conda-osx.cfg
  compass/machines/cori-haswell.cfg
  compass/machines/cori-knl.cfg
  compass/machines/grizzly.cfg
  conda/albany_supported.txt
  conda/bootstrap.py
  conda/compass_env/build.template
  conda/compass_env/load_compass.template
  conda/default.cfg
  conda/shared.py
  conda/spack/badger_gnu_mvapich.yaml
  conda/spack/badger_gnu_openmpi.yaml
  conda/unsupported.txt
  docs/design_docs/compass_package.rst
  docs/developers_guide/machines/anvil.rst
  docs/developers_guide/machines/badger.rst
  docs/developers_guide/machines/chrysalis.rst
  docs/developers_guide/machines/compy.rst
  docs/developers_guide/machines/cori.rst
  docs/developers_guide/machines/grizzly.rst
  docs/developers_guide/machines/index.rst
  docs/developers_guide/quick_start.rst
  docs/users_guide/machines/anvil.rst
  docs/users_guide/machines/badger.rst
  docs/users_guide/machines/chrysalis.rst
  docs/users_guide/machines/compy.rst
  docs/users_guide/machines/cori.rst
  docs/users_guide/machines/grizzly.rst
  docs/users_guide/machines/index.rst
  docs/users_guide/quick_start.rst
Labels: enhancement, deployment

#357 Automatically get `cores_per_node` on single node
  compass/machines/default.cfg
  compass/parallel.py
  docs/users_guide/machines/index.rst
  docs/users_guide/quick_start.rst
  example_configs/landice.cfg
  example_configs/ocean.cfg
Labels: clean-up, framework

#350 Change test cases to run like suites
  compass/__main__.py
  compass/run/__init__.py
  compass/run/serial.py
  compass/setup.py
  docs/developers_guide/api.rst
  docs/developers_guide/framework.rst
Labels: clean-up, framework

#359 Update to scorpio 1.3.2
  compass/version.py
  conda/bootstrap.py
  conda/compass_env/spec-file.template
  conda/default.cfg
  conda/recipe/meta.yaml
  conda/scorpio/recipe/build.sh
  conda/scorpio/recipe/meta.yaml
Labels: enhancement, deployment

#351 Add Greenland mesh generation test case
  compass/landice/tests/greenland/__init__.py
  compass/landice/tests/greenland/high_res_mesh/__init__.py
  compass/landice/tests/greenland/high_res_mesh/high_res_mesh.cfg
  compass/landice/tests/greenland/mesh.py
  docs/developers_guide/landice/api.rst
  docs/developers_guide/landice/test_groups/greenland.rst
  docs/users_guide/landice/test_groups/greenland.rst
Labels: enhancement, land ice

#366 Fix a typo in error message in env setup
  conda/bootstrap.py
Labels: bug, deployment

#367 Disable timing in scorpio build
  compass/version.py
  conda/bootstrap.py
  conda/recipe/meta.yaml
Labels: bug, deployment

#364 Set `OPENMP=true` in load script by default
  conda/bootstrap.py
  conda/shared.py
Labels: clean-up, deployment

#365 Switch `CompassConfigParser` to descend from `MpasConfigParser`
  compass/config.py
  conda/compass_env/spec-file.template
  conda/recipe/meta.yaml
  docs/developers_guide/api.rst
  docs/developers_guide/framework.rst
Labels: clean-up, framework

#369 Print runtime for tests as suite runs
  compass/run/serial.py
Labels: enhancement, framework

#371 Skip permissions update if not needed
  conda/bootstrap.py
Labels: clean-up, deployment

#372 Don't remove `esmf` from conda environment
  conda/bootstrap.py
Labels: clean-up, deployment

#375 Fix version import in compass load package
  compass/load/__init__.py
  conda/recipe/meta.yaml
Labels: bug

#378 Create basic config for an MPAS core
  compass/provenance.py
  compass/setup.py
Labels: clean-up, framework

#379 Optionally build load scripts for multiple compilers/MPIs at the same time
  conda/bootstrap.py
  conda/shared.py
  conda/unsupported.txt
Labels: enhancement, deployment

#380 Simplify output from config compass and load script
  conda/bootstrap.py
  conda/compass_env/load_compass.template
  conda/configure_compass_env.py
  conda/shared.py
Labels: clean-up, deployment

#318 Add calving law tests for Humboldt test group
  compass/landice/suites/fo_integration.txt
  compass/landice/suites/full_integration.txt
  compass/landice/suites/humboldt_calving_tests.txt
  compass/landice/suites/humboldt_calving_tests_fo.txt
  compass/landice/tests/dome/run_model.py
  compass/landice/tests/humboldt/__init__.py
  compass/landice/tests/humboldt/albany_input.yaml
  compass/landice/tests/humboldt/decomposition_test/__init__.py
  compass/landice/tests/humboldt/humboldt.cfg
  compass/landice/tests/humboldt/mesh.py
  compass/landice/tests/humboldt/mesh_gen/__init__.py
  compass/landice/tests/humboldt/namelist.landice
  compass/landice/tests/humboldt/restart_test/__init__.py
  compass/landice/tests/humboldt/restart_test/namelist.full
  compass/landice/tests/humboldt/restart_test/namelist.restart
  compass/landice/tests/humboldt/restart_test/namelist.restart.rst
  compass/landice/tests/humboldt/restart_test/streams.full
  compass/landice/tests/humboldt/restart_test/streams.restart
  compass/landice/tests/humboldt/restart_test/streams.restart.rst
  compass/landice/tests/humboldt/run_model.py
  compass/landice/tests/humboldt/streams.landice.template
  docs/developers_guide/landice/api.rst
  docs/developers_guide/landice/test_groups/humboldt.rst
  docs/developers_guide/landice/test_groups/index.rst
  docs/users_guide/landice/index.rst
  docs/users_guide/landice/suites.rst
  docs/users_guide/landice/test_groups/humboldt.rst
  docs/users_guide/landice/test_groups/index.rst
Labels: land ice

#376 Write out a job script for suite and test cases during setup
  compass/default.cfg
  compass/job/__init__.py
  compass/job/template.sh
  compass/machines/badger.cfg
  compass/machines/cori-haswell.cfg
  compass/setup.py
  docs/users_guide/quick_start.rst
Labels: enhancement, framework
