Repository MPAS-Dev/compass, pull requests merged in 2023-01, with the labels that each got.

#469 Reorganize ISOMIP+ steps
  compass/ocean/tests/isomip_plus/cull_mesh.py
  compass/ocean/tests/isomip_plus/forward.py
  compass/ocean/tests/isomip_plus/geom.py
  compass/ocean/tests/isomip_plus/initial_state.py
  compass/ocean/tests/isomip_plus/isomip_plus.cfg
  compass/ocean/tests/isomip_plus/isomip_plus_test.py
  compass/ocean/tests/isomip_plus/planar_mesh.py
  compass/ocean/tests/isomip_plus/process_geom.py
  compass/ocean/tests/isomip_plus/ssh_adjustment.py
  compass/ocean/tests/isomip_plus/viz/plot.py
Labels: ocean, clean-up

#490 Update shapely, geometric_features and mpas_tools
  conda/compass_env/spec-file.template
  conda/recipe/meta.yaml
Labels: deployment

#470 Fix `landIceFraction` in ISOMIP+
  compass/ocean/tests/isomip_plus/initial_state.py
  compass/ocean/tests/isomip_plus/viz/plot.py
Labels: bug, ocean

#491 Fix docs for matrix utility
  utils/matrix/README.md
Labels: documentation

#493 Replace deprecated `importlib.resources.path()` call
  conda/bootstrap.py
Labels: deployment

#504 Fix base env update in Azure tests
  azure-pipelines.yml
Labels: deployment

#496 Update to compass v1.2.0-alpha.4 and mache v1.10.0
  compass/version.py
  conda/albany_supported.txt
  conda/bootstrap.py
  conda/compass_env/spec-file.template
  conda/configure_compass_env.py
  conda/recipe/meta.yaml
  conda/unsupported.txt
  docs/developers_guide/machines/cori.rst
  docs/developers_guide/machines/index.rst
  docs/developers_guide/machines/perlmutter.rst
  docs/users_guide/machines/anvil.rst
  docs/users_guide/machines/cori.rst
  docs/users_guide/machines/perlmutter.rst
  utils/matrix/setup_matrix.py
Labels: enhancement, framework

#505 Fix ISOMIP+ docs
  compass/ocean/tests/isomip_plus/geom.py
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/test_groups/isomip_plus.rst
Labels: documentation

#508 Fix handling of ntasks = 1 for single node
  compass/parallel.py
Labels: bug, framework

#509 Update conda pnetcdf and scorpio versions
  conda/bootstrap.py
  conda/compass_env/spec-file.template
  conda/otps/ci/linux.yaml
  conda/pnetcdf/ci/linux_mpi_mpich.yaml
  conda/pnetcdf/ci/linux_mpi_openmpi.yaml
  conda/pnetcdf/ci/osx_mpi_mpich.yaml
  conda/pnetcdf/ci/osx_mpi_openmpi.yaml
  conda/pnetcdf/recipe/build.sh
  conda/pnetcdf/recipe/conda_build_config.yaml
  conda/pnetcdf/recipe/meta.yaml
  conda/scorpio/ci/linux_mpi_mpich.yaml
  conda/scorpio/ci/linux_mpi_openmpi.yaml
  conda/scorpio/ci/osx_mpi_mpich.yaml
  conda/scorpio/ci/osx_mpi_openmpi.yaml
  conda/scorpio/recipe/build.sh
  conda/scorpio/recipe/conda_build_config.yaml
  conda/scorpio/recipe/meta.yaml
  conda/shared.py
Labels: enhancement, deployment

#511 Fix deployment using python 2
  conda/shared.py
Labels: bug, deployment

#494 Add chicoma-cpu support
  compass/machines/chicoma-cpu.cfg
  conda/albany_supported.txt
  conda/petsc_supported.txt
  conda/unsupported.txt
  docs/developers_guide/machines/chicoma.rst
  docs/developers_guide/machines/index.rst
  docs/users_guide/machines/chicoma.rst
  docs/users_guide/machines/index.rst
  docs/users_guide/quick_start.rst
  utils/matrix/setup_matrix.py
Labels: enhancement, framework

#514 Fix code for not adding mamba to .bashrc
  conda/shared.py
Labels: bug, deployment

#518 Add pep8 guidance to docs
  docs/developers_guide/quick_start.rst
Labels: documentation
