Repository MPAS-Dev/compass, pull requests merged in 2024-01, with the labels that each got.

#751 Remove mamba commands and switch to Miniforge
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  conda/bootstrap.py
  conda/compass_env/load_compass.template
  conda/configure_compass_env.py
  conda/shared.py
  docs/developers_guide/deploying_spack.rst
  docs/developers_guide/ocean/test_groups/drying_slope.rst
  docs/developers_guide/quick_start.rst
  docs/tutorials/dev_add_rrm.rst
  docs/tutorials/dev_add_test_group.rst
  docs/tutorials/dev_porting_legacy.rst
  docs/users_guide/machines/index.rst
  docs/users_guide/quick_start.rst
  utils/e3sm_update/README.md
Labels: clean-up, dependencies and deployment

#745 Update namelist options for recent changes to Redi and Adams-Bashforth 2
  compass/ocean/tests/global_ocean/__init__.py
  compass/ocean/tests/global_ocean/analysis_test/__init__.py
  compass/ocean/tests/global_ocean/daily_output_test/__init__.py
  compass/ocean/tests/global_ocean/decomp_test/__init__.py
  compass/ocean/tests/global_ocean/dynamic_adjustment/__init__.py
  compass/ocean/tests/global_ocean/files_for_e3sm/write_coeffs_reconstruct/__init__.py
  compass/ocean/tests/global_ocean/forward.py
  compass/ocean/tests/global_ocean/init/ssh_adjustment.py
  compass/ocean/tests/global_ocean/mesh/arrm10to60/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/ec30to60/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/kuroshio12to60/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/kuroshio8to60/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/qu/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/qu240/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/rrs6to18/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/so12to60/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/wc14/__init__.py
  compass/ocean/tests/global_ocean/mesh/wc14/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/monthly_output_test/__init__.py
  compass/ocean/tests/global_ocean/namelist.forward
  compass/ocean/tests/global_ocean/performance_test/__init__.py
  compass/ocean/tests/global_ocean/restart_test/__init__.py
  compass/ocean/tests/global_ocean/restart_test/namelist.split_explicit_ab2.full
  compass/ocean/tests/global_ocean/restart_test/namelist.split_explicit_ab2.restart
  compass/ocean/tests/global_ocean/restart_test/streams.split_explicit_ab2.full
  compass/ocean/tests/global_ocean/restart_test/streams.split_explicit_ab2.restart
  compass/ocean/tests/global_ocean/threads_test/__init__.py
  compass/ocean/tests/gotm/default/namelist.forward
  compass/ocean/tests/isomip_plus/namelist.forward_and_ssh_adjust
  compass/ocean/tests/sphere_transport/correlated_tracers_2d/correlated_tracers_2d.cfg
  compass/ocean/tests/sphere_transport/divergent_2d/divergent_2d.cfg
  compass/ocean/tests/sphere_transport/nondivergent_2d/nondivergent_2d.cfg
  compass/ocean/tests/sphere_transport/rotation_2d/rotation_2d.cfg
Labels: enhancement, ocean, E3SM PR finished

#740 Add info about viewing compiled docs via www at NERSC
  docs/developers_guide/building_docs.rst
Labels: documentation

#757 Several fixes to deployment
  conda/bootstrap.py
Labels: bug, dependencies and deployment

#760 Fix jigsaw build
  conda/bootstrap.py
Labels: bug, dependencies and deployment

#761 Add dependabot for github actions
  .github/dependabot.yml
Labels: ci
