Repository MPAS-Dev/compass, pull requests merged in 2024-09, with the labels that each got.

#856 Update supported python versions
  .github/workflows/build_workflow.yml
  ci/generate.py
  ci/linux_mpi_mpich_python3.12.yaml
  ci/linux_mpi_nompi_python3.12.yaml
  ci/linux_mpi_openmpi_python3.12.yaml
  ci/osx_mpi_mpich_python3.12.yaml
  ci/osx_mpi_nompi_python3.12.yaml
  ci/osx_mpi_openmpi_python3.12.yaml
  conda/compass_env/spec-file.template
  conda/default.cfg
  docs/developers_guide/quick_start.rst
  setup.py
Labels: dependencies and deployment

#858 Tweak behaviors of CI workflows
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
Labels: ci

#859 Chicoma debug
  compass/job/__init__.py
  compass/job/job_script.template
  compass/machines/chicoma-cpu.cfg
  docs/developers_guide/machines/chicoma.rst
  docs/users_guide/machines/chicoma.rst
Labels: framework

#857 Update to 1.5.0-alpha.1
  compass/job/__init__.py
  compass/job/job_script.template
  compass/machines/pm-gpu.cfg
  compass/parallel.py
  compass/version.py
  conda/albany_supported.txt
  conda/bootstrap.py
  conda/compass_env/spec-file.template
  conda/configure_compass_env.py
  conda/default.cfg
  conda/unsupported.txt
Labels: dependencies and deployment

#807 New Mesh: SOwISC12to30E3r3
  compass/ocean/plot.py
  compass/ocean/suites/so12to30.txt
  compass/ocean/suites/so12to60.txt
  compass/ocean/suites/sowisc12to30.txt
  compass/ocean/suites/sowisc12to60.txt
  compass/ocean/tests/global_ocean/__init__.py
  compass/ocean/tests/global_ocean/init/initial_state.py
  compass/ocean/tests/global_ocean/mesh/__init__.py
  compass/ocean/tests/global_ocean/mesh/so12to30/__init__.py
  compass/ocean/tests/global_ocean/mesh/so12to30/dynamic_adjustment.yaml
  compass/ocean/tests/global_ocean/mesh/so12to30/high_res_region.geojson
  compass/ocean/tests/global_ocean/mesh/so12to30/namelist.init
  compass/ocean/tests/global_ocean/mesh/so12to30/namelist.split_explicit_ab2
  compass/ocean/tests/global_ocean/mesh/so12to30/so12to30.cfg
  compass/ocean/tests/global_ocean/mesh/so12to60/__init__.py
  compass/ocean/tests/global_ocean/mesh/so12to60/atlantic.geojson
  docs/developers_guide/ocean/api.rst
  docs/developers_guide/ocean/test_groups/global_ocean.rst
  docs/developers_guide/organization.rst
  docs/tutorials/dev_add_rrm.rst
  docs/users_guide/ocean/test_groups/global_ocean.rst
  docs/users_guide/quick_start.rst
  docs/users_guide/test_suites.rst
Labels: new mesh, ocean, E3SM PR finished, sea ice

#860 Add additional flags to `pip install` command
  conda/bootstrap.py
  conda/configure_compass_env.py
  docs/developers_guide/quick_start.rst
Labels: documentation, dependencies and deployment
